### ISSUE TITLE
考虑增加一个可执行的任务的选项

### ISSUE THREAD

**Issue by kanoyami** [DhyanaChina/todo-live#7]
在选择任务种类的时候可以增加一个可执行文件的选项。
当执行todo do命令的时候会在bash执行这个指令，我觉得后期应该是会有完成时间的选项的，配合上这个就可以提供一个简单的自动脚本执行的功能了。
我实现了一个小的演示，在我fork里。

**Comment by WittBulter** [comment]
没有问题。
在描述里增加一个语法判断，用约定解决脚本，比如 `des: bash: ~/xxxx/run.sh`，以固定 `bash` 或 `shell` 开头将会自动执行一个脚本。
然后 `do` 命令增加一个选项，比如 `-r` 手动触发命令。
还需要增加一个截至时间，对于截至时间如何添加你有什么好的想法吗？ (比如在对话时增加一个可选项还是以增加一个语法去识别？)

**Comment by kanoyami** [comment]
使用增加一个额外选项是一个简单高效的方法，其实是不是可以利用自动任务为todo live增加一个提醒呢？

**Comment by WittBulter** [comment]
如果加入了自动任务，提醒也是没问题的，因为会有一个常驻进程了。
但是在终端里面填时间不是很方便，很容易出现格式错误。

**Comment by kanoyami** [comment]
引入一个常驻进程是否意味着作为一个服务来运行？不考虑跨平台的话，是不是可以直接调用crontab？
当然，做成一个服务也是很棒的。

**Comment by WittBulter** [comment]
本身 NodeJS 跨平台还是很方便的，可以考虑用一个 Node 进程来搞定这些事。
其实这样普通任务也可以增加一个时间限制，到时间没有完成就推送一条提醒也不错。只是时间的输入需要考量一下？

**Comment by kanoyami** [comment]
那就开启一个进程吧，时间的输入确实有些困难，使用一个规则来匹配还要保证和系统时间比对的正确性。

Kanoyami
CARCH,SKL,ICT
________________________________

**Comment by WittBulter** [comment]
点错...
这周内可以先做一个版本，你可以来 PR review

**Comment by kanoyami** [comment]
好的。其实我想单独维护一个分支，想当贡献者

Kanoyami
CARCH,SKL,ICT
________________________________

**Comment by kanoyami** [comment]
我在想是不是可以参考crontab的时间定义模式，可以方便的定义需要循环多次的任务。但是对于一个只需要执行一次的任务来说会有点繁琐。

**Comment by WittBulter** [comment]
#9 solved
